// AUTO-GENERATED by scripts/generate-home-gallery.mjs — re-run to shuffle layout.
// Seed: 20260531
import type { ProjectImage } from "@/content/types";
import { projectAsset } from "@/lib/project-media";

export type HomeGalleryItem = {
  slug: string;
  title: string;
  image: ProjectImage;
  /** 1-based column start on the 4-column home grid. */
  colStart: number;
  /** Columns spanned (1 or 2). */
  colSpan: 1 | 2;
  /** Vertical stagger within the row (grid subunits). */
  offsetSubunits: number;
};

export type HomeGalleryRow = {
  items: HomeGalleryItem[];
};

export const homeGalleryRows: HomeGalleryRow[] = [
  {
    items: [
      {
        slug: "parliament-sports-complex",
        title: "Parliament Sports Complex",
        image: projectAsset("/images/projects/parliament-sports-complex", "side-street.webp", "Side street", 2000, 2500),
        colStart: 1,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "parliament-sports-complex",
        title: "Parliament Sports Complex",
        image: projectAsset("/images/projects/parliament-sports-complex", "cricket-practice.webp", "Cricket practice", 2000, 2500),
        colStart: 3,
        colSpan: 2,
        offsetSubunits: 2,
      },
    ],
  },
  {
    items: [
      {
        slug: "16-units-above-a-city-brewery",
        title: "16 Units Above a City Brewery",
        image: projectAsset("/images/projects/16-units-above-a-city-brewery", "facade.webp", "Facade", 4000, 2500),
        colStart: 1,
        colSpan: 2,
        offsetSubunits: 0,
      },
      {
        slug: "shack-in-the-paddyfield",
        title: "Shack in the Paddyfield",
        image: projectAsset("/images/projects/shack-in-the-paddyfield", "hut in seasons.jpg", "Hut in seasons", 4960, 1562),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 2,
      },
    ],
  },
  {
    items: [
      {
        slug: "breathe-on-the-land",
        title: "Breathe on the Land",
        image: projectAsset("/images/projects/breathe-on-the-land", "grassland dosmesticity.webp", "Grassland domesticity", 1016, 1224),
        colStart: 2,
        colSpan: 1,
        offsetSubunits: 0,
      },
    ],
  },
  {
    items: [
      {
        slug: "shack-in-the-paddyfield",
        title: "Shack in the Paddyfield",
        image: projectAsset("/images/projects/shack-in-the-paddyfield", "farm with the hut.webp", "Farm with the hut", 1166, 1244),
        colStart: 1,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "4WD in motion 1.gif", "4WD in motion", 516, 688),
        colStart: 3,
        colSpan: 1,
        offsetSubunits: 2,
      },
    ],
  },
  {
    items: [
      {
        slug: "parliament-sports-complex",
        title: "Parliament Sports Complex",
        image: projectAsset("/images/projects/parliament-sports-complex", "model.webp", "Parliament Sports Complex model", 6240, 4160),
        colStart: 2,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "16-units-above-a-city-brewery",
        title: "16 Units Above a City Brewery",
        image: projectAsset("/images/projects/16-units-above-a-city-brewery", "history 1.webp", "History", 4000, 2500),
        colStart: 3,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "shack-in-the-paddyfield",
        title: "Shack in the Paddyfield",
        image: projectAsset("/images/projects/shack-in-the-paddyfield", "sabusawa rice - traditional craft.webp", "Sabusawa rice craft", 1752, 744),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 1,
      },
    ],
  },
  {
    items: [
      {
        slug: "shack-in-the-paddyfield",
        title: "Shack in the Paddyfield",
        image: projectAsset("/images/projects/shack-in-the-paddyfield", "context mapping.jpg", "Context mapping", 3323, 2918),
        colStart: 1,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "breathe-on-the-land",
        title: "Breathe on the Land",
        image: projectAsset("/images/projects/breathe-on-the-land", "open air corridor.jpg", "Open air corridor", 4000, 3000),
        colStart: 3,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "16-units-above-a-city-brewery",
        title: "16 Units Above a City Brewery",
        image: projectAsset("/images/projects/16-units-above-a-city-brewery", "summer morning.webp", "Summer morning", 4000, 2500),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 2,
      },
    ],
  },
  {
    items: [
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "dam.gif", "Dam", 553, 737),
        colStart: 1,
        colSpan: 1,
        offsetSubunits: 0,
      },
    ],
  },
  {
    items: [
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "ranger station 1.png", "Ranger station", 4961, 7016),
        colStart: 1,
        colSpan: 2,
        offsetSubunits: 0,
      },
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "station to wetland 1.gif", "Station to wetland", 553, 737),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 2,
      },
    ],
  },
  {
    items: [
      {
        slug: "breathe-on-the-land",
        title: "Breathe on the Land",
        image: projectAsset("/images/projects/breathe-on-the-land", "main facade.png", "Main facade", 4000, 1700),
        colStart: 1,
        colSpan: 2,
        offsetSubunits: 0,
      },
      {
        slug: "16-units-above-a-city-brewery",
        title: "16 Units Above a City Brewery",
        image: projectAsset("/images/projects/16-units-above-a-city-brewery", "beer garden.webp", "Beer garden", 4000, 2500),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 1,
      },
    ],
  },
  {
    items: [
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "4WD on thte field 1.png", "4WD on the field", 4961, 7016),
        colStart: 1,
        colSpan: 2,
        offsetSubunits: 0,
      },
    ],
  },
  {
    items: [
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "future report.mp4", "Future report", 1920, 1080),
        colStart: 3,
        colSpan: 2,
        offsetSubunits: 1,
      },
    ],
  },
  {
    items: [
      {
        slug: "parliament-sports-complex",
        title: "Parliament Sports Complex",
        image: projectAsset("/images/projects/parliament-sports-complex", "sports-hall.webp", "Sports hall", 2000, 2500),
        colStart: 1,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "breathe-on-the-land",
        title: "Breathe on the Land",
        image: projectAsset("/images/projects/breathe-on-the-land", "co working.png", "Co-working", 4000, 2700),
        colStart: 2,
        colSpan: 1,
        offsetSubunits: 2,
      },
      {
        slug: "breathe-on-the-land",
        title: "Breathe on the Land",
        image: projectAsset("/images/projects/breathe-on-the-land", "childcare.png", "Childcare", 4000, 2700),
        colStart: 3,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "4WD in motion 2.png", "4WD in motion", 2076, 2768),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 0,
      },
    ],
  },
  {
    items: [
      {
        slug: "shack-in-the-paddyfield",
        title: "Shack in the Paddyfield",
        image: projectAsset("/images/projects/shack-in-the-paddyfield", "paddy field hut.png", "Paddy field hut", 2000, 2500),
        colStart: 3,
        colSpan: 1,
        offsetSubunits: 0,
      },
      {
        slug: "eternal-voyage",
        title: "Eternal Voyage",
        image: projectAsset("/images/projects/eternal-voyage", "water infrastrucutre.png", "Water infrastructure", 1500, 3074),
        colStart: 4,
        colSpan: 1,
        offsetSubunits: 1,
      },
    ],
  },
];
